taskset -c 0 ./cpu-hog &
taskset -c 2 ./cpu-hog &
taskset -c 4 ./cpu-hog &
#taskset -c 6 ./cpu-hog &
#taskset -c 8 ./cpu-hog &
#taskset -c 10 ./cpu-hog &
#taskset -c 12 ./cpu-hog &
#taskset -c 14 ./cpu-hog &
#taskset -c 16 ./cpu-hog &
#taskset -c 18 ./cpu-hog &
#taskset -c 20 ./cpu-hog &
#taskset -c 22 ./cpu-hog &
#taskset -c 24 ./cpu-hog &
#taskset -c 26 ./cpu-hog &
