all:
	g++ -std=c++11 -O3 -o timer timer.cc -lrt
	g++ -std=c++11 -O3 -o timer_stability timer_stability.cc -lrt
	g++ -std=c++11 -O3 -o tsc_freq tsc_freq.cc -lrt

clean:
	rm -f *.o timer timer_stability
