" All system-wide defaults are set in $VIMRUNTIME/debian.vim (usually just
" /usr/share/vim/vimcurrent/debian.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vim/vimrc), since debian.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing debian.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the
" following enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
"if has("autocmd")
"  filetype plugin indent on
"endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set nocompatible              " be iMproved, required

"Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

" YouCompleteMe
if v:version > 704 || (v:version == 704 && has('patch143'))
  Plugin 'Valloric/YouCompleteMe'
  filetype off                  " required
  set completeopt-=preview " Disable YCM scratch preview
  let g:ycm_confirm_extra_conf=0 " Disable YCM config load prompt
  let g:ycm_complete_in_strings = 1
  let g:ycm_complete_in_comments = 1
  "let g:ycm_cache_omnifunc = 0 " Disable cache
  nnoremap <C-]> :YcmCompleter GoToDefinition<CR>
  nnoremap <C-g> :YcmCompleter GoToDeclaration<CR>
endif

" Fuzzy file open
set rtp+=~/.fzf
let $FZF_DEFAULT_COMMAND = 'ag -g ""' " Respect .gitignore. Needs bashrc changes
let g:fzf_action = {
  \ 'enter': 'vsplit',
  \ 'ctrl-x': 'split'} " Open in vertical split by default. Ctrl-X for horizontal
nmap :fsp :FZF<Enter>

" Auto pairs
Plugin 'auto-pairs-gentle'

" greplace
Plugin 'skwp/greplace.vim'

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

set number

syntax on
filetype on
au BufNewFile,BufRead *.ispc set filetype=c
au BufNewFile,BufRead *.pg set filetype=gnuplot

colorscheme apprentice
set background=light
hi Comment ctermfg=Cyan

let &colorcolumn=join(range(81,81),",")
highlight ColorColumn ctermbg=235 guibg=#2c2d27

"Remap split switching to use Alt
nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>

"Quit all vim splits
nmap :qq :qa<Enter>

"Use TAB to complete when typing words, else inserts TABs as usual.
"Uses dictionary and source files to find matching words to complete.

"See help completion for source,
"Note: usual completion is on <C-n> but more trouble to press all the time.
"Never type the same word twice and maybe learn a new spellings!
"Use the Linux dictionary when spelling is in doubt.
"Window users can copy the file to their machine.
function! Tab_Or_Complete()
  if col('.')>1 && strpart( getline('.'), col('.')-2, 3 ) =~ '^\w'
    return "\<C-N>"
  else
    return "\<Tab>"
  endif
endfunction
:inoremap <Tab> <C-R>=Tab_Or_Complete()<CR>

"Do not search included boost headers during Tab completion
set include=^\\s*#\\s*include\ \\(<boost/\\)\\@!

"set statusline+=%F
set laststatus=2

"Ignore whitespace im vimdiff
"if &diff
"    set diffopt+=iwhite
"endif

set tabstop=2
set shiftwidth=2
set expandtab
set autoindent
set smartindent

" Automatically open, but do not go to (if there are errors) the quickfix /
" location list window, or close it when is has become empty.
"
" Note: Must allow nesting of autocmds to enable any customizations for quickfix
" buffers.
" Note: Normally, :cwindow jumps to the quickfix window if the command opens it
" (but not if it's already open). However, as part of the autocmd, this doesn't
" seem to happen.
autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow

set tags=./tags,tags;

call vundle#end()
filetype plugin indent on

