#!/usr/bin/env bash

if [ ! -d /sys/class/infiniband ]; then
  exit -1
fi
ibdevs=$(ls /sys/class/infiniband/)

devs=""
for netpath in /sys/class/net/*
do
  if (grep 0x15b3 ${netpath}/device/vendor > /dev/null 2>&1); then
    devs="$devs ${netpath##*/}"
  fi
done

if [ "x$devs" == "x" ]; then
  exit
fi

for d in $ibdevs; do
  ibrsc=$(cat /sys/class/infiniband/$d/device/resource)
  eths=$(ls /sys/class/net/)
  for eth in $eths; do
    filepath_resource=/sys/class/net/$eth/device/resource

    if [ -f $filepath_resource ]; then
      ethrsc=$(cat $filepath_resource)
      if [ "x$ethrsc" == "x$ibrsc" ]; then
        filepath_devid=/sys/class/net/$eth/dev_id
        filepath_devport=/sys/class/net/$eth/dev_port
        if [ -f $filepath_devid ]; then
          port1=0
          if [ -f $filepath_devport ]; then
            port1=$(cat $filepath_devport)
            port1=$(printf "%d" $port1)
          fi

          port=$(cat $filepath_devid)
          port=$(printf "%d" $port)
          if [ $port1 -gt $port ]; then
            port=$port1
          fi

          port=$(( port + 1 ))

          filepath_carrier=/sys/class/net/$eth/carrier

          if [ -f $filepath_carrier ]; then
            link_state=$(cat $filepath_carrier 2> /dev/null)
            if (( link_state == 1 )); then
              link_state="Up"
            else
              link_state="Down"
            fi
          else
            link_state="NA"
          fi

          echo "$d port $port ==> $eth ($link_state)"
        fi
      fi
    fi
  done
done
